services:
  - type: web
    name: loan-app
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false &&
      blitz build &&
      blitz prisma migrate deploy --preview-feature
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: loan-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: loan-db
    plan: starter
